name: Documentation Linting

on:
  pull_request:
    branches: [main]

jobs:
  lint-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.mlc_config.json'

      - name: Check Required Metadata
        run: |
          if ! grep -qE "^Version:\s[0-9]+\.[0-9]+\.[0-9]+" README.md; then
            echo "Missing or invalid version metadata!"
            exit 1
          fi
